# Generated by Django 4.2.7 on 2025-12-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_movie_type_alter_movie_poster_reviewlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Adventure', 'Adventure'), ('Sci-Fi', 'Science Fiction'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Animation', 'Animation'), ('Documentary', 'Documentary')], max_length=50),
        ),
    ]
