# Generated by Django 4.2.7 on 2025-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Science Fiction'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Animation', 'Animation'), ('Documentary', 'Documentary')], max_length=50),
        ),
    ]
